[package]
name = "chibivox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
jpreprocess = { version = "0.6.3", features = ["naist-jdic"] }
ndarray = "0.15.6"
once_cell = "1.19.0"
ort = "2.0.0-alpha.4"
regex = "1.10.3"
wav_io = "0.1.12"
